### ISSUE TITLE
In the version of OSL I am using 'orthogonalize' does not work but 'orthogonalise' does 

### ISSUE THREAD

**Issue by u01ai11** [OHBA-analysis/Quinn2018_TaskHMM#1]
https://github.com/OHBA-analysis/Quinn2018_TaskHMM/blob/1f48359016c26b1cec0f92447a2c69cb9cd808eb/scripts/hmm_2_envelope_estimation.m#L46

**Comment by AJQuinn** [comment]
Good spot. This updated after I had finalised the analysis in the paper but is correct for current versions. I'll commit a fix
